In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv('../data/raw/student_performance.csv')

In [3]:
print(df.head())

   Student_ID  Age      Gender  Attendance  Study_Hours  \
0           1   21        Male        79.3         19.5
1           2   18      Female       100.0         15.4
2           3   19      Female        95.1         23.7
3           4   21  Non-Binary        92.0          2.6
4           5   17      Female        90.1         22.6

   Assignments_Completed Participation  Previous_Grades Internet_Access  \
0                      8        Medium             64.9             Yes
1                      3        Medium             78.5             Yes
2                     10        Medium             59.6              No
3                      9        Medium             69.3             Yes
4                      5           Low             79.6             Yes

  Family_Support  Exam_Score  At_Risk Risk_Level
0           High       100.0        0   Low Risk
1           High        85.5        0   Low Risk
2         Medium       100.0        0   Low Risk
3            Low        83.1        1   Low Risk
4         Medium        94.4        0   Low Risk

In [4]:
print(df.tail())

        Student_ID  Age  Gender  Attendance  Study_Hours  \
999995      999996   18  Female        91.8          9.6
999996      999997   22  Female        79.4          8.9
999997      999998   22  Female        83.4          8.2
999998      999999   22  Female        78.8         14.5
999999     1000000   19  Female        90.4         14.7

        Assignments_Completed Participation  Previous_Grades Internet_Access  \
999995                      4           Low            100.0             Yes
999996                      7          High             52.5             Yes
999997                      1        Medium             63.2             Yes
999998                      1           Low             93.4             Yes
999999                     10          High             56.3             Yes

       Family_Support  Exam_Score  At_Risk Risk_Level
999995            Low        85.0        0   Low Risk
999996         Medium        88.3        0   Low Risk
999997         Medium        62.9        1   Low Risk
999998         Medium        92.5        0   Low Risk
999999            Low        99.6        0   Low Risk

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Student_ID             1000000 non-null  int64
 1   Age                    1000000 non-null  int64
 2   Gender                 1000000 non-null  object
 3   Attendance             1000000 non-null  float64
 4   Study_Hours            1000000 non-null  float64
 5   Assignments_Completed  1000000 non-null  int64
 6   Participation          1000000 non-null  object
 7   Previous_Grades        1000000 non-null  float64
 8   Internet_Access        1000000 non-null  object
 9   Family_Support         1000000 non-null  object
 10  Exam_Score             1000000 non-null  float64
 11  At_Risk                1000000 non-null  int64
 12  Risk_Level             1000000 non-null  object
dtypes: float64(4), int64(4), object(5)
memory usage: 99.2+ MB
None

In [6]:
print(df.shape)

(1000000, 13)

In [7]:
print(df.columns.tolist())

['Student_ID', 'Age', 'Gender', 'Attendance', 'Study_Hours', 'Assignments_Completed', 'Participation', 'Previous_Grades', 'Internet_Access', 'Family_Support', 'Exam_Score', 'At_Risk', 'Risk_Level']

In [8]:
print(df.isnull().sum())

Student_ID               0
Age                      0
Gender                   0
Attendance               0
Study_Hours              0
Assignments_Completed    0
Participation            0
Previous_Grades          0
Internet_Access          0
Family_Support           0
Exam_Score               0
At_Risk                  0
Risk_Level               0
dtype: int64

In [9]:
df.describe()

,Student_ID,Age,Attendance,Study_Hours,Assignments_Completed,Previous_Grades,Exam_Score,At_Risk
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,18.500897,84.701919,15.089317,5.000898,74.691435,90.205612,0.250517
std,288675.278932,2.290806,9.430208,7.775093,3.161381,14.390282,9.432195,0.433311
min,1.000000,15.000000,38.700000,0.000000,0.000000,4.000000,36.000000,0.000000
25%,250000.750000,17.000000,78.300000,9.600000,2.000000,64.800000,83.900000,0.000000
50%,500000.500000,19.000000,85.000000,15.000000,5.000000,75.000000,92.000000,0.000000
75%,750000.250000,21.000000,91.700000,20.400000,8.000000,85.100000,100.000000,1.000000
max,1000000.000000,22.000000,100.000000,40.000000,10.000000,100.000000,100.000000,1.000000

In [10]:
print(df.shape)

(1000000, 13)

In [11]:
print(df.head())

   Student_ID  Age      Gender  Attendance  Study_Hours  \
0           1   21        Male        79.3         19.5
1           2   18      Female       100.0         15.4
2           3   19      Female        95.1         23.7
3           4   21  Non-Binary        92.0          2.6
4           5   17      Female        90.1         22.6

   Assignments_Completed Participation  Previous_Grades Internet_Access  \
0                      8        Medium             64.9             Yes
1                      3        Medium             78.5             Yes
2                     10        Medium             59.6              No
3                      9        Medium             69.3             Yes
4                      5           Low             79.6             Yes

  Family_Support  Exam_Score  At_Risk Risk_Level
0           High       100.0        0   Low Risk
1           High        85.5        0   Low Risk
2         Medium       100.0        0   Low Risk
3            Low        83.1        1   Low Risk
4         Medium        94.4        0   Low Risk

In [12]:
print(df['Exam_Score'].describe())

count    1000000.000000
mean          90.205612
std            9.432195
min           36.000000
25%           83.900000
50%           92.000000
75%          100.000000
max          100.000000
Name: Exam_Score, dtype: float64

In [13]:
def create_risk(score):
    if score < 40:
        return "High Risk"
    elif score < 60:
        return "Medium Risk"
    else:
        return "Low Risk"

df["Risk_Level"] = df["Exam_Score"].apply(create_risk)

In [14]:
print(df.head())

   Student_ID  Age      Gender  Attendance  Study_Hours  \
0           1   21        Male        79.3         19.5
1           2   18      Female       100.0         15.4
2           3   19      Female        95.1         23.7
3           4   21  Non-Binary        92.0          2.6
4           5   17      Female        90.1         22.6

   Assignments_Completed Participation  Previous_Grades Internet_Access  \
0                      8        Medium             64.9             Yes
1                      3        Medium             78.5             Yes
2                     10        Medium             59.6              No
3                      9        Medium             69.3             Yes
4                      5           Low             79.6             Yes

  Family_Support  Exam_Score  At_Risk Risk_Level
0           High       100.0        0   Low Risk
1           High        85.5        0   Low Risk
2         Medium       100.0        0   Low Risk
3            Low        83.1        1   Low Risk
4         Medium        94.4        0   Low Risk

In [15]:
print(df.columns.to_list())

['Student_ID', 'Age', 'Gender', 'Attendance', 'Study_Hours', 'Assignments_Completed', 'Participation', 'Previous_Grades', 'Internet_Access', 'Family_Support', 'Exam_Score', 'At_Risk', 'Risk_Level']

In [16]:
print(df.shape)

(1000000, 13)

In [17]:
print(df["Risk_Level"].value_counts())

Risk_Level
Low Risk       996652
Medium Risk      3345
High Risk           3
Name: count, dtype: int64

In [18]:
print(df["Risk_Level"].value_counts(normalize=True) * 100)

Risk_Level
Low Risk       99.6652
Medium Risk     0.3345
High Risk       0.0003
Name: proportion, dtype: float64

In [19]:
print(df["Exam_Score"].describe())

count    1000000.000000
mean          90.205612
std            9.432195
min           36.000000
25%           83.900000
50%           92.000000
75%          100.000000
max          100.000000
Name: Exam_Score, dtype: float64

In [20]:
print(df["Exam_Score"].quantile([0.05,0.10,0.20,0.25,0.30,0.40,0.50]))

0.05    72.4
0.10    76.7
0.20    81.9
0.25    83.9
0.30    85.7
0.40    89.0
0.50    92.0
Name: Exam_Score, dtype: float64

In [21]:
q20 = df["Exam_Score"].quantile(0.20)
q50 = df["Exam_Score"].quantile(0.50)

def create_risk(score):
    if score <= q20:
        return "High Risk"
    elif score <= q50:
        return "Medium Risk"
    else:
        return "Low Risk"

In [22]:
print(df["Exam_Score"].quantile([0.05,0.10,0.20,0.25,0.30,0.40,0.50]))

0.05    72.4
0.10    76.7
0.20    81.9
0.25    83.9
0.30    85.7
0.40    89.0
0.50    92.0
Name: Exam_Score, dtype: float64

In [23]:
threshold = df["Exam_Score"].quantile(0.25)

df["At_Risk"] = (
    df["Exam_Score"] <= threshold
).astype(int)

In [24]:
print(df["At_Risk"].value_counts())
print(df["At_Risk"].value_counts(normalize=True) * 100)

At_Risk
0    749483
1    250517
Name: count, dtype: int64
At_Risk
0    74.9483
1    25.0517
Name: proportion, dtype: float64

In [25]:
threshold = df["Exam_Score"].quantile(0.25)

df["At_Risk"] = (
    df["Exam_Score"] <= threshold
).astype(int)

df.to_csv(
    "../data/raw/student_performance.csv",
    index=False
)

In [26]:
df = pd.read_csv("../data/raw/student_performance.csv")
print(df.columns.tolist())

['Student_ID', 'Age', 'Gender', 'Attendance', 'Study_Hours', 'Assignments_Completed', 'Participation', 'Previous_Grades', 'Internet_Access', 'Family_Support', 'Exam_Score', 'At_Risk', 'Risk_Level']

In [27]:
print(df.shape)

(1000000, 13)

In [28]:
train = pd.read_csv("../artifacts/train.csv")
test = pd.read_csv("../artifacts/test.csv")
print(train.shape)
print(test.shape)
print(train.columns.tolist())

print(train["At_Risk"].value_counts(normalize=True))

print(test["At_Risk"].value_counts(normalize=True))

(800000, 11)
(200000, 11)
['Age', 'Gender', 'Attendance', 'Study_Hours', 'Assignments_Completed', 'Participation', 'Previous_Grades', 'Internet_Access', 'Family_Support', 'At_Risk', 'Risk_Level']
At_Risk
0    0.749483
1    0.250518
Name: proportion, dtype: float64
At_Risk
0    0.749485
1    0.250515
Name: proportion, dtype: float64

In [29]:
import pandas as pd

train = pd.read_csv("../artifacts/train.csv")

print(train.dtypes)

Age                        int64
Gender                    object
Attendance               float64
Study_Hours              float64
Assignments_Completed      int64
Participation             object
Previous_Grades          float64
Internet_Access           object
Family_Support            object
At_Risk                    int64
Risk_Level                object
dtype: object

In [30]:
import pickle

with open(
    "../artifacts/preprocessor.pkl",
    "rb"
) as file:
    preprocessor = pickle.load(file)

print(type(preprocessor))

<class 'sklearn.compose._column_transformer.ColumnTransformer'>

C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator ColumnTransformer from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [31]:
print(preprocessor.transformers)

[('num', Pipeline(steps=[('scaler', StandardScaler())]), ['Age', 'Attendance', 'Study_Hours', 'Assignments_Completed', 'Previous_Grades']), ('cat', Pipeline(steps=[('encoder', OneHotEncoder(handle_unknown='ignore'))]), ['Gender', 'Participation', 'Internet_Access', 'Family_Support'])]

In [32]:
import pandas as pd

train = pd.read_csv("../artifacts/train.csv")

X = train.drop(columns=["At_Risk"])

X_transformed = preprocessor.transform(X.head())

print(X_transformed.shape)

(5, 16)

In [33]:
train = pd.read_csv("../artifacts/train.csv")

print(train["At_Risk"].value_counts())

At_Risk
0    599586
1    200414
Name: count, dtype: int64

In [34]:
import pickle

model = pickle.load(
    open("../artifacts/model.pkl", "rb")
)

print(model.classes_)

[0 1]

C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [35]:
import pandas as pd

df = pd.read_csv("../data/raw/student_performance.csv")

threshold = df["Exam_Score"].quantile(0.25)

print("Threshold:", threshold)

print(
    df[df["Exam_Score"] <= threshold]
    [["Exam_Score"]]
    .describe()
)

Threshold: 83.9
          Exam_Score
count  250517.000000
mean       76.840814
std         5.800158
min        36.000000
25%        73.700000
50%        78.200000
75%        81.400000
max        83.900000

In [36]:
df.groupby("At_Risk")[[
    "Attendance",
    "Study_Hours",
    "Assignments_Completed",
    "Previous_Grades"
]].mean()

         Attendance  Study_Hours  Assignments_Completed  Previous_Grades
At_Risk
0         85.668960    16.777353               5.542421        77.372343
1         81.808779    10.039146               3.380801        66.670841

In [37]:
df.groupby("At_Risk")[[
    "Attendance",
    "Study_Hours",
    "Assignments_Completed",
    "Previous_Grades"
]].mean()

         Attendance  Study_Hours  Assignments_Completed  Previous_Grades
At_Risk
0         85.668960    16.777353               5.542421        77.372343
1         81.808779    10.039146               3.380801        66.670841

In [38]:
import pandas as pd
import pickle

model = pickle.load(
    open("../artifacts/model.pkl", "rb")
)

preprocessor = pickle.load(
    open("../artifacts/preprocessor.pkl", "rb")
)

feature_names = (
    preprocessor.get_feature_names_out()
)

coef_df = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": model.coef_[0]
})

coef_df = coef_df.sort_values(
    by="Coefficient"
)

print(coef_df)

                       Feature  Coefficient
2             num__Study_Hours    -1.836867
4         num__Previous_Grades    -1.497397
3   num__Assignments_Completed    -1.406856
12    cat__Internet_Access_Yes    -1.188841
8      cat__Participation_High    -0.992304
13    cat__Family_Support_High    -0.892644
1              num__Attendance    -0.834432
15  cat__Family_Support_Medium    -0.298620
6             cat__Gender_Male    -0.209570
7       cat__Gender_Non-Binary    -0.205455
5           cat__Gender_Female    -0.200846
10   cat__Participation_Medium    -0.102808
0                     num__Age     0.007603
9       cat__Participation_Low     0.479242
11     cat__Internet_Access_No     0.572970
14     cat__Family_Support_Low     0.575393

C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\91825\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator ColumnTransformer from version 1.9.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [39]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/student_performance.csv"
)

print(
    df["Assignments_Completed"].describe()
)

count    1000000.000000
mean           5.000898
std            3.161381
min            0.000000
25%            2.000000
50%            5.000000
75%            8.000000
max           10.000000
Name: Assignments_Completed, dtype: float64